import type { Plant } from "../types";

export const bodembedekkers: Plant[] = [
  {id:154,naam:'Maagdenpalm',latijn:'Vinca minor',cat:'bodembedekker',emoji:'🌿',zon:'schaduw',water:'weinig',wg:'wintergroen',h:0.15,eco:{ins:2,vog:0,bes:0},v:{3:['Bloei – blauw/violet'],4:['Bloei'],5:['Groei – snel'],6:['Snoeien indien nodig om te beheersen'],12:['Wintergroen']}},
  {id:158,naam:'Pachysandra',latijn:'Pachysandra terminalis',cat:'bodembedekker',emoji:'🌿',zon:'schaduw',water:'weinig',wg:'wintergroen',h:0.2,eco:{ins:1,vog:0,bes:0},v:{2:['Oud of beschadigd blad bijknippen'],3:['Groei begint'],4:['Bloei – kleine witte bloempjes'],5:['Bloei aflopend','Groei zet door'],6:['Snel uitbreiden – ideale bodembedekker'],8:['Snoeien indien te uitbundig'],9:['Groei vertraagt'],12:['Wintergroen – blijft groen en decoratief']}},
  {id:186,naam:'Penningkruid',latijn:'Lysimachia nummularia',cat:'bodembedekker',emoji:'🌿',zon:'schaduw',water:'matig',wg:'wintergroen',h:0.1,eco:{ins:1,vog:0,bes:0},v:{4:['Gele bloempjes'],5:['Bloei – kruipend tapijt'],6:['Bloei aflopend'],7:['Groei beheersen indien nodig'],9:['Eventueel verdelen en herplanten'],10:['Wintergroen – blijft groen']}},
  {id:187,naam:'Kruipend Zenegroen',latijn:'Ajuga reptans',cat:'bodembedekker',emoji:'🌿',zon:'schaduw',water:'matig',wg:'wintergroen',h:0.15,eco:{ins:3,vog:0,bes:0},v:{3:['Blauwe bloeiaren'],4:['Bloei'],5:['Uitlopers terugsnijden als plant te ver kruipt'],9:['Eventueel verdelen en herplanten'],10:['Wintergroen – biedt dekking voor insecten'],12:['Wintergroen']}},
  {id:188,naam:'Aardbeiklaver',latijn:'Waldsteinia ternata',cat:'bodembedekker',emoji:'🌿',zon:'schaduw',water:'weinig',wg:'halfwintergroen',h:0.15,eco:{ins:2,vog:0,bes:0},v:{4:['Gele bloemetjes'],5:['Bloei aflopend'],6:['Uitlopers beheersen'],9:['Eventueel verdelen'],10:['Blad blijft grotendeels staan – weinig onderhoud']}},
  {id:189,naam:'Gevlekte Dovenetel',latijn:'Lamium maculatum',cat:'bodembedekker',emoji:'🌿',zon:'schaduw',water:'matig',wg:'halfwintergroen',h:0.2,eco:{ins:3,vog:0,bes:0},v:{4:['Roze of witte bloempjes'],5:['Bloei'],6:['Bloei aflopend'],7:['Terugknijpen voor compacte groei'],9:['Compost rondom aanbrengen'],11:['Blad blijft deels groen']}},
];
