import type { Plant } from "../types";

export const bollen: Plant[] = [
  {id:3,naam:'Tulp',latijn:'Tulipa',cat:'bol',emoji:'🌷',zon:'beide',water:'weinig',wg:'bladverliezen',h:0.3,eco:{ins:1,vog:0,bes:0},v:{1:['Controleer of bollen droog staan'],2:['Eerste scheuten verwachten'],4:['Bloeitijd – geniet ervan!'],5:['Blad laten staan tot het geel is – energie opslaan'],6:['Bollen uitgraven en drogen'],7:['Bollen opslaan op droge plek'],9:['Bollen planten (10–15 cm diep)'],10:['Bollen planten voor de grond bevriest']}},
  {id:4,naam:'Narcis',latijn:'Narcissus',cat:'bol',emoji:'🌼',zon:'beide',water:'weinig',wg:'bladverliezen',h:0.3,eco:{ins:1,vog:0,bes:0},v:{2:['Eerste scheuten doorbreken'],3:['Bloeitijd nadert'],4:['Bloeitijd','Verwelkte bloemen verwijderen'],5:['Blad laten staan tot het geel wordt'],6:['Blad verwijderen als het geel is'],9:['Nieuwe bollen planten'],10:['Bollen planten voor vorst']}},
  {id:5,naam:'Hyacint',latijn:'Hyacinthus orientalis',cat:'bol',emoji:'💜',zon:'beide',water:'weinig',wg:'bladverliezen',h:0.25,eco:{ins:1,vog:0,bes:0},v:{2:['Eerste scheuten zichtbaar'],3:['Bloeitijd – sterk geurend'],4:['Verwelkte bloemen verwijderen','Blad laten staan'],5:['Blad vergeelt – energie terug naar bol'],8:['Bollen planten'],9:['Bollen planten (10 cm diep)'],10:['Inplanten voor vorst']}},
  {id:6,naam:'Dahlia',latijn:'Dahlia',cat:'bol',emoji:'🌸',zon:'zon',water:'matig',wg:'bladverliezen',h:0.8,eco:{ins:2,vog:0,bes:0},v:{3:['Begin met voorkiemen binnen'],4:['Uitplanten na last frost (midden april)'],5:['Inknijpen voor meer bloemen','Staken plaatsen'],6:['Bemesten met kaliumrijke meststof'],7:['Bloeitijd','Dode bloemen verwijderen'],8:['Water geven','Bemesten'],9:['Bloeitijd'],10:['Na eerste vorst: knollen uitgraven'],11:['Knollen opslaan op vorstvrije plek'],12:['Bewaren – controleer op rot']}},
  {id:99,naam:'Anemoon',latijn:'Anemone',cat:'bol',emoji:'🌸',zon:'beide',water:'matig',wg:'bladverliezen',h:0.4,eco:{ins:2,vog:0,bes:0},v:{3:['Knollen weken in water, dan planten'],4:['Opkomst'],5:['Bloei'],6:['Blad laten staan na bloei'],7:['Knollen uitgraven en drogen'],8:['Knollen bewaren'],10:['Knollen planten voor vorstvrije herfst']}},
  {id:100,naam:'Gladiool',latijn:'Gladiolus',cat:'bol',emoji:'🌸',zon:'zon',water:'matig',wg:'bladverliezen',h:1,eco:{ins:1,vog:0,bes:0},v:{4:['Knollen planten (gefaseerd voor langere bloei)'],5:['Knollen planten – laatste ronde'],6:['Scheuten komen op'],7:['Bloei'],8:['Bloei'],9:['Uitgraven na bloei – wacht op vorst'],10:['Knollen drogen en bewaren op vorstvrije plek'],12:['Controleer knollen op rot']}},
  {id:133,naam:'Krokus',latijn:'Crocus spp.',cat:'bol',emoji:'🌷',zon:'zon',water:'weinig',wg:'bladverliezen',h:0.1,eco:{ins:3,vog:0,bes:0},v:{2:['Bloei – vroeg!'],3:['Bloei'],4:['Blad geel – laten staan'],5:['Blad verdwijnt'],9:['Planten voor herfst'],10:['Planten']}},
  {id:134,naam:'Sierui',latijn:'Allium spp.',cat:'bol',emoji:'🌸',zon:'zon',water:'weinig',wg:'bladverliezen',h:0.6,eco:{ins:3,vog:0,bes:0},v:{3:['Bladgroei'],4:['Bladgroei – soms al blad'],5:['Bloei – grote ronde bloemen'],6:['Bloei'],7:['Zaadkoppen – decoratief laten'],9:['Planten voor najaar'],10:['Planten']}},
  {id:135,naam:'Blauw Druifje',latijn:'Muscari armeniacum',cat:'bol',emoji:'🔵',zon:'zon',water:'weinig',wg:'bladverliezen',h:0.2,eco:{ins:2,vog:0,bes:0},v:{2:['Bladgroei'],3:['Bloei'],4:['Bloei'],5:['Blad geel – laten staan'],9:['Planten of verdelen'],10:['Planten']}},
  {id:136,naam:'Sneeuwklokje',latijn:'Galanthus nivalis',cat:'bol',emoji:'❄️',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:0.15,eco:{ins:2,vog:0,bes:0},v:{1:['Bloei – vroegste bol!'],2:['Bloei'],3:['Blad geel'],4:['Verdelen "in het groen" na bloei'],9:['Droge bollen planten'],10:['Planten']}},
  {id:137,naam:'Winterakoniet',latijn:'Eranthis hyemalis',cat:'bol',emoji:'🌼',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:0.1,eco:{ins:2,vog:0,bes:0},v:{1:['Bloei – geel, met kraag'],2:['Bloei'],3:['Blad verdwijnt'],4:['Verdelen na bloei'],9:['Planten – week bollen voor planten'],10:['Planten']}},
  {id:178,naam:'Kievitsbloem',latijn:'Fritillaria meleagris',cat:'bol',emoji:'🔔',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:0.3,eco:{ins:2,vog:0,bes:0},v:{9:['Bollen planten in vochthoudende grond'],10:['Bollen planten voor de grond bevriest'],3:['Eerste bladeren zichtbaar'],4:['Elegante geruite bloemen – typisch Nederlands'],5:['Blad afsterven – niet verwijderen']}},
  {id:179,naam:'Blauwe Sterhyacint',latijn:'Scilla siberica',cat:'bol',emoji:'💙',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:0.15,eco:{ins:2,vog:0,bes:0},v:{9:['Bollen planten op 8 cm diepte'],10:['Bollen planten'],3:['Intensief blauwe bloemen – vroeg in het voorjaar'],4:['Blad afsterven – niet verwijderen']}},
  {id:180,naam:'Sneeuwroem',latijn:'Chionodoxa luciliae',cat:'bol',emoji:'🌟',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:0.1,eco:{ins:2,vog:0,bes:0},v:{9:['Bollen planten'],10:['Bollen planten'],2:['Vroege stervormige bloemen – blauw/wit/roze'],3:['Bloei'],4:['Blad langzaam afsterven']}},
  {id:181,naam:'Lenteklokje',latijn:'Leucojum vernum',cat:'bol',emoji:'🔔',zon:'halfschaduw',water:'veel',wg:'bladverliezen',h:0.2,eco:{ins:2,vog:0,bes:0},v:{9:['Bollen planten in vochtige humusrijke grond'],2:['Witte klokvormige bloemen met groene stipjes'],3:['Bloei'],4:['Blad afsterven – grond vochtig houden']}},
  {id:182,naam:'Camassia',latijn:'Camassia leichtlinii',cat:'bol',emoji:'💜',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:0.6,eco:{ins:2,vog:0,bes:0},v:{9:['Bollen planten op 15 cm diepte'],10:['Bollen planten'],5:['Blauwe of witte bloeiaren'],6:['Blad afsterven – niet storen']}},
];
