import type { Plant } from "../types";

export const bomen: Plant[] = [
  {id:30,naam:'Appelboom',latijn:'Malus domestica',cat:'boom',emoji:'🍎',zon:'zon',water:'matig',wg:'bladverliezen',h:5,eco:{ins:3,vog:2,bes:1},v:{1:['Wintersnoeien kan'],2:['Wintersnoeien afronden'],3:['Bemesten'],4:['Bloesem – bescherm bij nachtvorst'],5:['Vruchtdunning (overtollige appels verwijderen)'],6:['Waterloten verwijderen'],7:['Oogst vroege rassen'],8:['Oogst zomerrassen'],9:['Oogst herfstrassen'],10:['Hoofdoogst','Gevallen appels opruimen'],11:['Beschermende spray tegen ziekten'],12:['Snoeien kan beginnen']}},
  {id:31,naam:'Perenboom',latijn:'Pyrus communis',cat:'boom',emoji:'🍐',zon:'zon',water:'matig',wg:'bladverliezen',h:6,eco:{ins:3,vog:2,bes:1},v:{1:['Wintersnoeien'],2:['Snoeien afronden'],3:['Bemesten'],4:['Bloesem'],5:['Vruchtdunning'],6:['Zijscheuten terugknippen'],8:['Vroege rassen oogsten'],9:['Oogst'],10:['Oogst late rassen','Gevallen peren opruimen'],11:['Snoeien kan']}},
  {id:32,naam:'Pruimenboom',latijn:'Prunus domestica',cat:'boom',emoji:'🟣',zon:'zon',water:'matig',wg:'bladverliezen',h:5,eco:{ins:3,vog:2,bes:1},v:{2:['Snoeien (vermijd grote wonden)'],3:['Bemesten'],4:['Bloesem'],5:['Vruchtdunning bij veel vruchten'],7:['Oogst vroege rassen'],8:['Oogst','Zomersnoei na oogst'],9:['Oogst late rassen']}},
  {id:33,naam:'Kersenboom',latijn:'Prunus avium',cat:'boom',emoji:'🍒',zon:'zon',water:'matig',wg:'bladverliezen',h:8,eco:{ins:3,vog:3,bes:1},v:{2:['Snoeien'],3:['Bemesten'],4:['Bloesem – bescherm bij nachtvorst'],6:['Vroege rassen rijpen','Vogels weren'],7:['Oogst','Net plaatsen voor vogels'],8:['Zomersnoei na oogst']}},
  {id:34,naam:'Magnolia',latijn:'Magnolia',cat:'boom',emoji:'🌸',zon:'beide',water:'matig',wg:'bladverliezen',h:5,eco:{ins:2,vog:0,bes:0},v:{3:['Bloeitijd bij vroeg voorjaar'],4:['Bloeitijd'],6:['Snoeien indien nodig – direct na bloei'],7:['Zomerbemesting'],10:['Mulchen'],11:['Jonge planten beschermen bij vorst']}},
  {id:35,naam:'Vlierboom',latijn:'Sambucus nigra',cat:'boom',emoji:'⚫',zon:'beide',water:'matig',wg:'bladverliezen',h:6,eco:{ins:3,vog:3,bes:1},v:{3:['Hard snoeien voor compacte groei'],4:['Bemesten'],6:['Bloesem oogsten voor vlierbloesemdrank'],7:['Bessen rijpen'],8:['Bessen oogsten voor jam/siroop'],9:['Nazomersnoei'],10:['Mulchen']}},
  {id:36,naam:'Hazelaar',latijn:'Corylus avellana',cat:'boom',emoji:'🟤',zon:'beide',water:'matig',wg:'bladverliezen',h:5,eco:{ins:2,vog:2,bes:1},v:{1:['Katjes – eerste teken van lente'],2:['Katjes bloeien – bestuiving'],3:['Snoeien na de bloei'],4:['Bemesten'],9:['Hazelnoten oogsten'],10:['Noten rijpen en vallen'],12:['Snoeien – open kroonvorm behouden']}},
  {id:37,naam:'Taxus',latijn:'Taxus baccata',cat:'boom',emoji:'🌲',zon:'schaduw',water:'weinig',wg:'wintergroen',h:10,eco:{ins:0,vog:3,bes:1},v:{4:['Bemesten'],6:['Scheren/snoeien'],8:['Laatste snoeibeurt voor winter'],9:['Rode bessen – giftig! Kinderen waarschuwen'],11:['Sneeuw uitkloppen'],12:['Vorstbestendig – weinig nodig']}},
  {id:38,naam:'Berk',latijn:'Betula pendula',cat:'boom',emoji:'🌳',zon:'beide',water:'matig',wg:'bladverliezen',h:15,eco:{ins:1,vog:2,bes:1},v:{3:['Niet snoeien (bloedt hevig)'],4:['Bladeren komen uit'],5:['Bladvlooien controleren'],9:['Herfstkleur'],10:['Bladeren opruimen (goed composteren)']}},
  {id:157,naam:'Olijfboom',latijn:'Olea europaea',cat:'boom',emoji:'🫒',zon:'zon',water:'weinig',wg:'wintergroen',h:5,eco:{ins:1,vog:1,bes:1},v:{3:['Voorzichtig naar buiten op zonnige dag – bescherm bij nachtvorst'],4:['Buiten zetten op warme plek'],5:['Snoeien voor mooie vorm'],6:['Bloei – kleine witte geurende bloemetjes'],7:['Bemesten met olijfboomenmest'],8:['Groei'],9:['Vruchten vormen – in NL zelden rijp'],10:['Naar binnen voor de nachtvorst'],11:['Koel maar vorstvrij overwinteren (5–10°C)'],12:['Minimaal water geven – rust']}},
  {id:163,naam:'Krentenboom',latijn:'Amelanchier lamarckii',cat:'boom',emoji:'🌸',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:6,eco:{ins:3,vog:3,bes:1},v:{3:['Planttijd – compost toevoegen'],4:['Bloei – witte bloesem bewonderen'],5:['Na bloei snoeien voor vormbehoud'],6:['Bessen oogsten'],7:['Bessen oogsten'],9:['Tweede bemesting met organische meststof'],10:['Genieten van herfstkleuren'],11:['Blad valt – decoratief']}},
  {id:164,naam:'Meidoorn',latijn:'Crataegus laevigata',cat:'boom',emoji:'🌿',zon:'zon',water:'weinig',wg:'bladverliezen',h:6,eco:{ins:3,vog:3,bes:1},v:{3:['Controleer op dode takken – verwijder indien nodig'],5:['Bloei – aantrekkelijk voor bestuivers'],6:['Licht snoeien na bloei'],9:['Rode bessen vormen – vogels aantrekken'],10:['Rode bessen – vogelvriendelijk'],11:['Ruststadium']}},
  {id:165,naam:'Sierpeer',latijn:'Pyrus calleryana',cat:'boom',emoji:'🌸',zon:'zon',water:'matig',wg:'bladverliezen',h:8,eco:{ins:2,vog:1,bes:1},v:{3:['Planttijd – watergeefschema starten voor jonge bomen'],4:['Rijke witte bloei'],5:['Regelmatig water geven bij droogte'],6:['Regelmatig water geven bij droogte'],7:['Regelmatig water geven bij droogte'],8:['Regelmatig water geven bij droogte'],9:['Bemesten met organische meststof'],10:['Herfstkleuren – blad valt']}},
  {id:166,naam:'Bolcatalpa',latijn:'Catalpa bignonioides',cat:'boom',emoji:'🌳',zon:'zon',water:'matig',wg:'bladverliezen',h:4,eco:{ins:2,vog:0,bes:0},v:{4:['Nieuwe bladeren uitlopen – bemesten'],6:['Grote tropische bladeren volop aanwezig'],7:['Witte bloemen op niet-geknipte exemplaren'],8:['Witte bloemen'],10:['Blad valt – opruimen']}},
];
