import type { Plant } from "../types";

export const fruit: Plant[] = [
  {id:70,naam:'Aardbei',latijn:'Fragaria x ananassa',cat:'fruit',emoji:'🍓',zon:'beide',water:'matig',wg:'halfwintergroen',h:0.2,eco:{ins:2,vog:1,bes:1},v:{3:['Onkruid wieden','Stro rond planten'],4:['Bemesten'],5:['Stro rond planten (geen rot)'],6:['Oogst','Uitlopers verwijderen of bewortelen'],7:['Oogst','Nieuwe planten van uitlopers'],8:['Oud blad verwijderen'],9:['Nieuwe planten uitplanten'],10:['Bemesten na seizoen'],11:['Afdekken met stro bij vorst']}},
  {id:71,naam:'Framboos',latijn:'Rubus idaeus',cat:'fruit',emoji:'🫐',zon:'beide',water:'matig',wg:'bladverliezen',h:1.5,eco:{ins:2,vog:2,bes:1},v:{2:['Snoeien: verwijder verouderde stelen'],3:['Bemesten'],4:['Nieuwe scheuten opbinden'],7:['Oogst','Geplukte stelen afknippen'],8:['Oogst'],9:['Herfsframboos oogst'],10:['Herfsframboos terugsnoeien tot op de grond']}},
  {id:72,naam:'Blauwe Bes',latijn:'Vaccinium corymbosum',cat:'fruit',emoji:'🫐',zon:'beide',water:'matig',wg:'bladverliezen',h:1.5,eco:{ins:2,vog:2,bes:1},v:{3:['Bemesten met zure mest'],4:['Bloesem – net tegen vogels'],5:['Net plaatsen'],7:['Oogst'],8:['Oogst'],9:['Oogst late rassen'],10:['Snoeien na bladval'],11:['Mulchen met dennenaalden (zuur)']}},
  {id:73,naam:'Rode Bes',latijn:'Ribes rubrum',cat:'fruit',emoji:'🔴',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:1.2,eco:{ins:2,vog:2,bes:1},v:{2:['Snoeien'],3:['Bemesten'],4:['Bloesem'],6:['Oogst'],7:['Oogst'],8:['Na oogst snoeien – oude takken verwijderen'],11:['Mulchen']}},
  {id:74,naam:'Kruisbes',latijn:'Ribes uva-crispa',cat:'fruit',emoji:'🟢',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:1.2,eco:{ins:2,vog:1,bes:1},v:{1:['Snoeien'],2:['Snoeien afronden'],3:['Bemesten'],5:['Vruchtdunning'],7:['Oogst'],8:['Oogst'],11:['Mulchen']}},
  {id:112,naam:'Vijg',latijn:'Ficus carica',cat:'fruit',emoji:'🫐',zon:'zon',water:'weinig',wg:'bladverliezen',h:4,eco:{ins:0,vog:2,bes:1},v:{3:['Bescherming verwijderen','Lichte snoei'],4:['Kleine vijgjes zichtbaar'],5:['Groei'],7:['Eerste oogst (overwinterde vijgjes)'],8:['Hoofdoogst'],9:['Oogst'],10:['Beschermen bij strenge vorst'],11:['Bescherming aanbrengen'],12:['Vorstbescherming']}},
  {id:113,naam:'Braam',latijn:'Rubus fruticosus',cat:'fruit',emoji:'🫐',zon:'beide',water:'matig',wg:'halfwintergroen',h:2,eco:{ins:2,vog:3,bes:1},v:{3:['Snoeien – verwijder 2-jarige takken die gedragen hebben'],4:['Nieuwe scheuten opbinden'],5:['Bloei – bijen!'],6:['Bloei'],7:['Oogst'],8:['Oogst'],9:['Oogst','Nieuwe loten opbinden voor volgend jaar']}},
  {id:114,naam:'Druif',latijn:'Vitis vinifera',cat:'fruit',emoji:'🍇',zon:'zon',water:'matig',wg:'bladverliezen',h:5,eco:{ins:1,vog:2,bes:1},v:{2:['Snoeien – voor einde februari!'],4:['Eerste bladeren'],5:['Bloei'],6:['Dunnen van trossen'],7:['Groei'],8:['Kleuring'],9:['Oogst'],10:['Oogst late rassen'],11:['Bladval']}},
];
