import type { Plant } from "../types";

export const grassen: Plant[] = [
  {id:75,naam:'Siergras',latijn:'Miscanthus sinensis',cat:'gras',emoji:'🌾',zon:'zon',water:'weinig',wg:'bladverliezen',h:2,eco:{ins:0,vog:2,bes:1},v:{3:['Afgestorven pollen terugknippen voor nieuwe groei'],8:['Bloeiaren vormen'],9:['Bloeiaren – mooi in het licht'],10:['Herfstkleuren'],11:['Laten staan voor wintereffect'],12:['Wintereffect – stelen laten staan']}},
  {id:76,naam:'Bamboe',latijn:'Phyllostachys',cat:'gras',emoji:'🎋',zon:'beide',water:'matig',wg:'wintergroen',h:5,eco:{ins:0,vog:1,bes:0},v:{4:['Nieuwe halmen komen op – bescherm indien nodig'],5:['Groei'],6:['Overtollige halmen verwijderen'],9:['Verwelkte bladeren opruimen'],11:['Inkuipen – wordt anders invasief!'],12:['Vorstbescherming bij jonge planten']}},
  {id:146,naam:'Vedergras',latijn:'Stipa tenuissima',cat:'siergras',emoji:'🌾',zon:'zon',water:'weinig',wg:'bladverliezen',h:0.6,eco:{ins:0,vog:1,bes:0},v:{2:['Oud gras terugknippen tot 10cm'],4:['Nieuwe groei'],6:['Pluimen verschijnen'],7:['Pluimen – goudgeel'],8:['Pluimen in wind'],9:['Goudbruin kleuren'],12:['Wintersilhouet decoratief']}},
  {id:147,naam:'Japans Siergras',latijn:'Miscanthus sinensis',cat:'siergras',emoji:'🌾',zon:'zon',water:'matig',wg:'bladverliezen',h:2,eco:{ins:0,vog:2,bes:1},v:{2:['Terugknippen tot 10-15cm'],4:['Nieuwe groei'],7:['Groei'],8:['Pluimen verschijnen'],9:['Pluimen – zilver/rood'],10:['Kleuren'],11:['Wintersilhouet'],12:['Wintersilhouet decoratief']}},
  {id:148,naam:'Blauwgras',latijn:'Helictotrichon sempervirens',cat:'siergras',emoji:'🌾',zon:'zon',water:'weinig',wg:'wintergroen',h:0.9,eco:{ins:0,vog:1,bes:0},v:{2:['Oud gras verwijderen'],3:['Groei'],5:['Pluimen'],6:['Pluimen – blauwgrijs blad het hele jaar'],12:['Wintergroen – blauw blad decoratief']}},
  {id:149,naam:'Zegge',latijn:'Carex spp.',cat:'siergras',emoji:'🌿',zon:'schaduw',water:'matig',wg:'halfwintergroen',h:0.5,eco:{ins:0,vog:1,bes:0},v:{2:['Oud blad wegknippen'],3:['Groei'],5:['Bloeiaren'],6:['Bloeiaren'],12:['Veel soorten wintergroen']}},
  {id:150,naam:'Pluimgras',latijn:'Calamagrostis × acutiflora',cat:'siergras',emoji:'🌾',zon:'zon',water:'matig',wg:'bladverliezen',h:1.5,eco:{ins:0,vog:2,bes:1},v:{2:['Terugknippen tot 15cm'],4:['Groei'],6:['Vroege pluimen – opvallend'],7:['Pluimen'],8:['Pluimen goudbruin'],10:['Wintersilhouet'],12:['Wintersilhouet']}},
  {id:192,naam:'Pijpenstrootje',latijn:'Molinia caerulea',cat:'gras',emoji:'🌾',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:0.9,eco:{ins:0,vog:1,bes:0},v:{3:['Oud gras terugknippen voor nieuwe uitloop'],4:['Nieuwe groene pollen'],7:['Elegante pluimen verschijnen'],8:['Pluimen'],9:['Pluimen'],10:['Goudgeel herfstkleur'],11:['Goudgeel herfstkleur'],12:['Decoratief skelet in de tuin']}},
  {id:193,naam:'Vingergras',latijn:'Panicum virgatum',cat:'gras',emoji:'🌾',zon:'zon',water:'weinig',wg:'bladverliezen',h:1.5,eco:{ins:0,vog:2,bes:1},v:{3:['Terugknippen tot 10 cm'],4:['Nieuwe uitloop'],7:['IJle pluimen boven sierlijk blad'],8:['Pluimen'],9:['Pluimen'],10:['Herfstkleur rood/oranje'],11:['Herfstkleur'],12:['Decoratief laten staan']}},
];
