import type { Plant } from "../types";

export const klimplanten: Plant[] = [
  {id:28,naam:'Kamperfoelie',latijn:'Lonicera',cat:'klimplant',emoji:'🌸',zon:'beide',water:'matig',wg:'halfwintergroen',h:4,eco:{ins:3,vog:3,bes:1},v:{3:['Snoeien en opbinden'],4:['Bemesten'],6:['Bloeitijd'],7:['Bloeitijd'],8:['Bloeitijd'],9:['Vruchten rijpen'],10:['Mulchen']}},
  {id:29,naam:'Wisteria',latijn:'Wisteria sinensis',cat:'klimplant',emoji:'💜',zon:'zon',water:'matig',wg:'bladverliezen',h:8,eco:{ins:2,vog:1,bes:0},v:{2:['Snoeien – zomerloten terugknippen tot 2–3 knoppen'],3:['Bemesten'],5:['Bloeitijd'],6:['Zomersnoei: nieuwe scheuten terugknippen'],7:['Zomersnoei'],8:['Zomersnoei'],10:['Tweede snoei'],11:['Winterbescherming bij jonge planten']}},
  {id:115,naam:'Clematis',latijn:'Clematis spp.',cat:'klimplant',emoji:'🌸',zon:'beide',water:'matig',wg:'halfwintergroen',h:5,eco:{ins:2,vog:1,bes:0},v:{2:['Snoeien groep 3 soorten (late bloei) terug tot 30cm'],3:['Snoeien groep 2 soorten – verwijder dood hout','Nieuwe scheuten opbinden'],4:['Snelle groei – opbinden'],5:['Eerste bloemen groep 1 en 2'],6:['Bloei'],7:['Bloei groep 3 soorten'],8:['Bloei'],9:['Laatste bloemen','Zaadbollen vormen zich'],11:['Bescherm wortels met mulch']}},
  {id:116,naam:'Klimop',latijn:'Hedera helix',cat:'klimplant',emoji:'🌿',zon:'schaduw',water:'weinig',wg:'wintergroen',h:10,eco:{ins:3,vog:3,bes:1},v:{3:['Terugsnoeien indien nodig'],4:['Nieuwe groei'],9:['Bessen vormen zich'],10:['Bessen rijpen – vogels!'],12:['Wintergroen']}},
  {id:117,naam:'Wilde Wingerd',latijn:'Parthenocissus quinquefolia',cat:'klimplant',emoji:'🍂',zon:'beide',water:'matig',wg:'bladverliezen',h:10,eco:{ins:1,vog:2,bes:1},v:{3:['Snoeien – houd in toom'],4:['Nieuwe blaadjes'],5:['Groei'],6:['Groei'],7:['Groei'],9:['Spectaculaire herfstkleuren – rood/oranje'],10:['Bladval']}},
  {id:118,naam:'Klimhortensia',latijn:'Hydrangea anomala subsp. petiolaris',cat:'klimplant',emoji:'🌸',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:10,eco:{ins:1,vog:1,bes:0},v:{3:['Licht snoeien'],4:['Bladvorming'],6:['Bloei – witte schermbloemige bloemen'],7:['Bloei'],9:['Herfstkleuren'],11:['Bladval']}},
  {id:119,naam:'Winterjasmijn',latijn:'Jasminum nudiflorum',cat:'klimplant',emoji:'🌼',zon:'beide',water:'weinig',wg:'halfwintergroen',h:3,eco:{ins:1,vog:1,bes:0},v:{1:['Bloei – gele bloemen op kale takken'],2:['Bloei'],3:['Bloei eindigt','Snoeien na bloei – verwijder oud hout'],4:['Nieuwe groei'],11:['Knoppen zichtbaar'],12:['Vroege knoppen']}},
  {id:183,naam:'Reukerwt',latijn:'Lathyrus odoratus',cat:'klimplant',emoji:'🌸',zon:'zon',water:'veel',wg:'bladverliezen',h:2,eco:{ins:2,vog:0,bes:0},v:{2:['Zaden vooraf weken en binnenshuis zaaien'],3:['Binnenshuis opkweken'],4:['Uitplanten na laatste nachtvorst – klimsteun plaatsen'],5:['Geurige bloemen – regelmatig plukken voor langere bloei'],6:['Plukken en water geven'],7:['Plukken en water geven'],8:['Plukken en water geven'],9:['Bloei aflopend – zaden bewaren'],10:['Plant sterft af na eerste vorst']}},
  {id:184,naam:'Klimmende Winde',latijn:'Ipomoea tricolor',cat:'klimplant',emoji:'💙',zon:'zon',water:'matig',wg:'bladverliezen',h:3,eco:{ins:2,vog:0,bes:0},v:{3:['Zaden binnenshuis zaaien'],4:['Opkweken – klimsteun bieden'],5:['Uitplanten na vorstvrij'],7:['Hemelsblauwe trompetbloemen'],8:['Bloei'],9:['Bloei aflopend'],10:['Plant sterft bij vorst – verwijderen']}},
];
