import type { Plant } from "../types";

export const kruiden: Plant[] = [
  {id:54,naam:'Basilicum',latijn:'Ocimum basilicum',cat:'kruid',emoji:'🌿',zon:'zon',water:'matig',wg:'bladverliezen',h:0.5,eco:{ins:2,vog:0,bes:0},v:{4:['Zaaien binnen (warm)'],5:['Uitplanten na vorst – warme plek'],6:['Regelmatig oogsten','Bloemen verwijderen'],7:['Oogsten','Bloemen verwijderen voor betere smaak'],8:['Oogsten'],9:['Pesto maken','Plant gaat na vorst'],10:['Eventueel binnen halen']}},
  {id:55,naam:'Rozemarijn',latijn:'Salvia rosmarinus',cat:'kruid',emoji:'🌿',zon:'zon',water:'weinig',wg:'wintergroen',h:1,eco:{ins:3,vog:0,bes:0},v:{3:['Snoeien na de winter'],4:['Bemesten licht'],6:['Bloeien','Stekken nemen'],7:['Stekken'],8:['Oogsten voor drogen'],10:['Beschermen bij harde vorst'],11:['Mulchen rond de basis']}},
  {id:56,naam:'Tijm',latijn:'Thymus vulgaris',cat:'kruid',emoji:'🌱',zon:'zon',water:'weinig',wg:'halfwintergroen',h:0.3,eco:{ins:3,vog:0,bes:0},v:{3:['Snoeien – terugknippen'],5:['Bloei','Bijen!'],6:['Bloei','Oogsten'],7:['Oogsten voor drogen'],8:['Snoeien na bloei'],9:['Oogsten'],11:['Beschermen bij strenge vorst']}},
  {id:57,naam:'Munt',latijn:'Mentha',cat:'kruid',emoji:'🌿',zon:'halfschaduw',water:'matig',wg:'halfwintergroen',h:0.5,eco:{ins:2,vog:0,bes:0},v:{3:['Snoeien – verwijder overgebleven stelen'],4:['Groei begint'],5:['Oogsten'],6:['Oogsten','Bloemen verwijderen'],7:['Inkuipen – wordt anders invasief!'],8:['Oogsten'],9:['Oogsten','Drogen'],10:['Terugsnoeien'],11:['Mulchen']}},
  {id:58,naam:'Peterselie',latijn:'Petroselinum crispum',cat:'kruid',emoji:'🌿',zon:'halfschaduw',water:'matig',wg:'halfwintergroen',h:0.3,eco:{ins:1,vog:0,bes:0},v:{3:['Zaaien (langzame kieming – geduld)'],4:['Zaaien'],5:['Opkomst','Dunnen'],6:['Oogsten'],7:['Oogsten'],8:['Oogsten'],9:['Oogsten'],10:['Afdekken voor winteroogst'],11:['Winteroogst mogelijk onder vliesdoek'],12:['Winteroogst']}},
  {id:59,naam:'Bieslook',latijn:'Allium schoenoprasum',cat:'kruid',emoji:'🌱',zon:'beide',water:'matig',wg:'bladverliezen',h:0.3,eco:{ins:2,vog:0,bes:0},v:{3:['Eerste scheuten – oogsten kan al'],4:['Oogsten','Bloemen zijn ook eetbaar'],5:['Oogsten','Bloemen eetbaar'],6:['Oogsten','Bloemen verwijderen voor meer blad'],7:['Oogsten'],8:['Oogsten'],9:['Oogsten'],10:['Terugknippen']}},
  {id:60,naam:'Dille',latijn:'Anethum graveolens',cat:'kruid',emoji:'🌿',zon:'zon',water:'matig',wg:'bladverliezen',h:0.8,eco:{ins:3,vog:1,bes:0},v:{4:['Zaaien buiten'],5:['Opkomst'],6:['Oogsten jong blad'],7:['Oogsten','Bloei'],8:['Zaad oogsten'],9:['Laatste oogst','Zaad verzamelen']}},
  {id:61,naam:'Oregano',latijn:'Origanum vulgare',cat:'kruid',emoji:'🌿',zon:'zon',water:'weinig',wg:'halfwintergroen',h:0.4,eco:{ins:3,vog:0,bes:0},v:{3:['Snoeien na de winter'],5:['Oogsten'],6:['Bloei','Bijen','Oogsten'],7:['Snoeien na bloei','Drogen'],8:['Drogen'],9:['Laatste oogst'],10:['Mulchen']}},
  {id:62,naam:'Salie',latijn:'Salvia officinalis',cat:'kruid',emoji:'🌿',zon:'zon',water:'weinig',wg:'halfwintergroen',h:0.5,eco:{ins:3,vog:0,bes:0},v:{3:['Snoeien'],5:['Bloei'],6:['Bloei','Bijen','Oogsten'],7:['Oogsten voor drogen'],8:['Drogen'],9:['Niet meer zwaar snoeien'],11:['Beschermen bij strenge vorst']}},
  {id:89,naam:'Koriander',latijn:'Coriandrum sativum',cat:'kruid',emoji:'🌿',zon:'beide',water:'matig',wg:'bladverliezen',h:0.5,eco:{ins:2,vog:0,bes:0},v:{4:['Zaaien buiten – haat verplanten'],5:['Opkomst – dun'],6:['Oogst blad'],7:['Bloei','Zaad oogsten voor kruiden'],8:['Zaad oogsten en drogen'],9:['Zaaien herfstrassen voor blad']}},
  {id:90,naam:'Dragon',latijn:'Artemisia dracunculus',cat:'kruid',emoji:'🌿',zon:'zon',water:'weinig',wg:'bladverliezen',h:1,eco:{ins:1,vog:0,bes:0},v:{3:['Snoeien'],4:['Scheuten verschijnen'],5:['Oogsten'],6:['Oogsten','Stelen inkorten'],7:['Oogsten – voor drogen'],8:['Drogen'],10:['Terugknippen'],11:['Mulchen']}},
  {id:91,naam:'Lavas',latijn:'Levisticum officinale',cat:'kruid',emoji:'🌿',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:2,eco:{ins:2,vog:0,bes:0},v:{3:['Nieuwe scheuten – voorzichtig oogsten'],4:['Fors groeien'],5:['Oogsten'],6:['Bloei','Zaad laten vormen'],7:['Oogsten – heeft sterke smaak'],8:['Zaad oogsten'],10:['Terugknippen']}},
  {id:92,naam:'Citroenmelisse',latijn:'Melissa officinalis',cat:'kruid',emoji:'🍋',zon:'halfschaduw',water:'matig',wg:'bladverliezen',h:0.6,eco:{ins:3,vog:0,bes:0},v:{3:['Eerste scheuten'],4:['Oogsten'],5:['Oogsten','Groeit snel'],6:['Bloei – bijen!'],7:['Snoeien na bloei','Tweede oogst'],8:['Oogsten'],9:['Terugknippen'],11:['Mulchen']}},
  {id:93,naam:'Kervel',latijn:'Anthriscus cerefolium',cat:'kruid',emoji:'🌿',zon:'halfschaduw',water:'matig',wg:'halfwintergroen',h:0.5,eco:{ins:1,vog:0,bes:0},v:{3:['Zaaien buiten – verdraagt kou'],4:['Oogst'],5:['Oogst'],6:['Zaad verzamelen','Opnieuw zaaien in schaduw'],8:['Zaaien herfst'],9:['Oogst herfst'],10:['Oogst']}},
  {id:94,naam:'Venkelkruid',latijn:'Foeniculum vulgare',cat:'kruid',emoji:'🌿',zon:'zon',water:'matig',wg:'bladverliezen',h:1.5,eco:{ins:3,vog:1,bes:0},v:{3:['Snoeien'],4:['Nieuwe scheuten'],5:['Oogsten'],6:['Bloei – aantrekkelijk voor insecten'],7:['Zaad vormt'],8:['Zaad oogsten'],9:['Zaad oogsten','Drogen'],10:['Terugknippen']}},
  {id:155,naam:'Valeriaan',latijn:'Valeriana officinalis',cat:'kruid',emoji:'🌸',zon:'beide',water:'matig',wg:'bladverliezen',h:1.5,eco:{ins:3,vog:0,bes:0},v:{2:['Verdelen indien nodig'],4:['Groei'],5:['Groei'],6:['Bloei – witte/roze pluimen'],7:['Bloei'],8:['Zaad rijpt'],9:['Snoeien']}},
  {id:196,naam:'Stevia',latijn:'Stevia rebaudiana',cat:'kruid',emoji:'🌿',zon:'zon',water:'matig',wg:'bladverliezen',h:0.6,eco:{ins:1,vog:0,bes:0},v:{3:['Zaaien binnenshuis of stekken'],4:['Opkweken'],5:['Uitplanten na vorstvrij'],6:['Bladeren oogsten'],7:['Bladeren oogsten – voor bloei het meest zoet'],8:['Grote oogst voor bloei'],9:['Laatste grote oogst'],10:['Binnenhalen – niet vorsthard']}},
];
