import type { Plant } from "../types";

export const varens: Plant[] = [
  {id:151,naam:'Eikvaren',latijn:'Polypodium vulgare',cat:'varen',emoji:'🌿',zon:'schaduw',water:'matig',wg:'wintergroen',h:0.3,eco:{ins:0,vog:0,bes:0},v:{3:['Nieuwe frondes'],4:['Groei'],5:['Volledig uitgegroeid'],9:['Sporen rijpen'],12:['Wintergroen']}},
  {id:152,naam:'Struisvaren',latijn:'Matteuccia struthiopteris',cat:'varen',emoji:'🌿',zon:'schaduw',water:'veel',wg:'bladverliezen',h:1.2,eco:{ins:0,vog:0,bes:0},v:{3:['Vorstbestendig – vroege groei'],4:['Frondes ontrollen – sierlijk'],5:['Volledig uitgegroeid – grote vaas'],6:['Sporendragers verschijnen'],11:['Afsterven'],12:['Sporendragers decoratief in winter']}},
  {id:153,naam:'Naaldvaren',latijn:'Polystichum setiferum',cat:'varen',emoji:'🌿',zon:'schaduw',water:'matig',wg:'halfwintergroen',h:0.8,eco:{ins:0,vog:0,bes:0},v:{2:['Oud blad wegknippen'],3:['Nieuwe frondes'],4:['Groei'],5:['Volledig uitgegroeid'],12:['Wintergroen of halfwintergroen']}},
  {id:159,naam:'Tongvaren',latijn:'Asplenium scolopendrium',cat:'varen',emoji:'🌿',zon:'schaduw',water:'matig',wg:'wintergroen',h:0.5,eco:{ins:0,vog:0,bes:0},v:{2:['Verwijder beschadigd oud blad'],3:['Nieuwe frondes beginnen te ontrollen'],4:['Groei'],5:['Volledig uitgegroeid – glanzend donkergroen blad'],9:['Sporen rijpen aan onderkant blad'],12:['Wintergroen – glanzend blad blijft decoratief']}},
  {id:190,naam:'Mannetjesvaren',latijn:'Dryopteris filix-mas',cat:'varen',emoji:'🌿',zon:'schaduw',water:'matig',wg:'halfwintergroen',h:1,eco:{ins:0,vog:0,bes:0},v:{2:['Oud blad wegknippen voor nieuwe groei'],4:['Nieuwe fronde-rollen ontvouwen'],5:['Decoratieve groene varenbladeren volgroeid'],9:['Grootse groene vaas op hoogtepunt'],10:['Oudste bladeren worden geel – verwijderen'],11:['Halfwintergroen – beschermt de wortels']}},
  {id:191,naam:'Japanse Schildvaren',latijn:'Athyrium nipponicum',cat:'varen',emoji:'🌿',zon:'schaduw',water:'matig',wg:'bladverliezen',h:0.5,eco:{ins:0,vog:0,bes:0},v:{3:['Oude stelen weghalen voor nieuwe groei'],4:['Nieuwe fronde-rollen met zilvergrijs blad ontvouwen'],5:['Decoratief zilverachtig blad'],6:['Volgroeide sierlijke frondes'],9:['Op hoogtepunt van schoonheid'],10:['Blad vergaat – verwijderen']}},
];
